import math
from typing import ClassVar, List

from pydantic import BaseModel, Field, model_validator

from backend.core.logging.workflow_logging import logger
from backend.domains.simulation.weights import normalize_weights


class InitialUserStateSchema(BaseModel):
    """Initial states of the simulation."""

    attention: float = Field(..., ge=0, le=100)
    fatigue: float = Field(..., ge=0, le=100)


class ResponseRatesSchema(BaseModel):
    """Response rates of state transitions."""

    attention: float = Field(..., ge=0, le=1)
    fatigue: float = Field(..., ge=0, le=1)


class EventThresholdsSchema(BaseModel):
    """Thresholds for triggering simulation events."""

    high_error_risk: float = Field(..., ge=0, le=100)
    very_high_cognitive_load: float = Field(..., ge=0, le=100)
    very_low_attention: float = Field(..., ge=0, le=100)
    time_pressure_warning: float = Field(15.0, ge=0, le=100)
    rework_error_risk: float = Field(62.0, ge=0, le=100)
    high_inhibition_load: float = Field(65.0, ge=0, le=100)
    task_switching_strain: float = Field(65.0, ge=0, le=100)


class ModelWeightsSchema(BaseModel):
    """
    Weights of the linear models.

    Defines how many input factors are present for each linear model.
    """

    WEIGHT_COUNTS: ClassVar[dict[str, int]] = {
        "text_complexity": 4,
        "navigation_effort": 3,
        "decoding_load": 4,
        "visual_reading_load": 4,
        "dyslexia_reading_load": 4,
        "sustained_attention_load": 4,
        "inhibition_load": 4,
        "attention_switching_load": 4,
        "adhd_interaction_load": 4,
        "reading_speed": 4,
        "attention": 6,
        "fatigue": 5,
        "cognitive_load": 5,
        "error_risk": 4,
        "task_success_score": 3,
        "completion_efficiency": 3,
    }
    LEGACY_WEIGHT_ALIASES: ClassVar[dict[str, str]] = {
        "task_success_probability": "task_success_score",
    }

    text_complexity: List[float] = Field(..., min_length=4, max_length=4)
    navigation_effort: List[float] = Field(..., min_length=3, max_length=3)
    decoding_load: List[float] = Field(..., min_length=4, max_length=4)
    visual_reading_load: List[float] = Field(..., min_length=4, max_length=4)
    dyslexia_reading_load: List[float] = Field(..., min_length=4, max_length=4)
    sustained_attention_load: List[float] = Field(..., min_length=4, max_length=4)
    inhibition_load: List[float] = Field(..., min_length=4, max_length=4)
    attention_switching_load: List[float] = Field(..., min_length=4, max_length=4)
    adhd_interaction_load: List[float] = Field(..., min_length=4, max_length=4)
    reading_speed: List[float] = Field(..., min_length=4, max_length=4)

    attention: List[float] = Field(
        ...,
        min_length=6,
        max_length=6,
        description=(
            "Weights in the order Distraction Sensitivity, "
            "Distractions, Time Pressure, Fatigue, "
            "Accessibility Support and Context Stability."
        ),
    )

    fatigue: List[float] = Field(..., min_length=5, max_length=5)
    cognitive_load: List[float] = Field(..., min_length=5, max_length=5)
    error_risk: List[float] = Field(..., min_length=4, max_length=4)
    task_success_score: List[float] = Field(
        ...,
        min_length=3,
        max_length=3,
    )
    completion_efficiency: List[float] = Field(
        ...,
        min_length=3,
        max_length=3,
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_weight_sets(cls, data):
        """
        Normalizes all weights before Pydantic validation.

        This also converts invalid weights generated by the LLM
        into valid weights automatically.
        """

        if not isinstance(data, dict):
            return data

        normalized_data = dict(data)
        for legacy_name, canonical_name in cls.LEGACY_WEIGHT_ALIASES.items():
            if (
                canonical_name not in normalized_data
                and legacy_name in normalized_data
            ):
                normalized_data[canonical_name] = normalized_data[legacy_name]
            normalized_data.pop(legacy_name, None)

        for field_name, factor_count in cls.WEIGHT_COUNTS.items():
            original = normalized_data.get(field_name, [])
            normalized = normalize_weights(original, factor_count)

            if original != normalized:
                logger.warning(
                    "NORMALIZE_SIMULATION_WEIGHTS field=%s input=%r normalized=%r",
                    field_name,
                    original,
                    normalized,
                )

            normalized_data[field_name] = normalized

        return normalized_data

    @model_validator(mode="after")
    def validate_weight_sets(self):
        """
        Performs a final check that all weights sum to 1.

        Due to prior normalization, this review should normally
        always succeed.
        """

        for field_name in type(self).model_fields:
            weights = getattr(self, field_name)

            if not math.isclose(
                sum(weights),
                1.0,
                rel_tol=1e-6,
                abs_tol=1e-6,
            ):
                raise ValueError(f"{field_name} weights must sum to 1")

        return self


class TaskStepModifierSchema(BaseModel):
    """
    Optional modifiers for individual task steps.

    This allows specific HTA/GOMS steps to be simulated as more or
    less demanding.
    """

    step_id: str
    attention_modifier: float = Field(1.0, ge=0, le=2)
    fatigue_modifier: float = Field(1.0, ge=0, le=2)
    reading_speed_modifier: float = Field(1.0, ge=0, le=2)
    reason: str


class SimulationModelSchema(BaseModel):
    """
    Structured description of the simulation configuration.

    The LLM provides this model as input for the actual Python simulation.
    The calculations themselves are then performed deterministically in
    the backend.
    """

    time_step_seconds: int = Field(1, ge=1, le=10)
    enable_task_abandonment: bool = True
    max_step_duration_factor: float = Field(3.0, ge=1.0, le=100.0)

    initial_user_state: InitialUserStateSchema
    response_rates: ResponseRatesSchema
    event_thresholds: EventThresholdsSchema
    model_weights: ModelWeightsSchema

    task_step_modifiers: List[TaskStepModifierSchema] = Field(default_factory=list)

    assumptions: List[str] = Field(default_factory=list)
